### PR TITLE
The third branch

### PR DESCRIPTION
**Pull request by Feruzka1706**
please review it

### CODE REVIEW

**Review by nazliSDET — APPROVED** [review]

**Comment by nazliSDET** [comment]
Take a rest Feruze!

**Review by ahmetYilmaz88 — APPROVED** [review]
accepted and approved your changes!

**Comment by ahmadsam33r** [comment]
I don't like his teaching way he is making so boring

**Review by ahmadsam33r — COMMENTED** [review]
done

**Pull request merged**
