### PR TITLE
Nazli friday02

### PR DESCRIPTION
**Pull request by nazliSDET**

### CODE REVIEW

**Comment by gulistan33** [comment]
nice!

**Comment by ahmadsam33r** [comment]
great job

**Comment by gulistan33** [comment]
hello

**Comment by ahmetYilmaz88** [comment]
reviewed

**Comment by gulistan33** [comment]
merged?

**Comment by ahmetYilmaz88** [comment]
Merging is blocked

**Comment by gulistan33** [comment]
still open?

**Comment by gulistan33** [comment]
yes.

**Review by ahmetYilmaz88 — APPROVED** [review]

**Review by ahmadsam33r — APPROVED** [review]

**Review by ahmetYilmaz88 — COMMENTED** [review]
done

**Review by gulistan33 — COMMENTED** [review]
done?

**Pull request merged**
