### PR TITLE
Login1file functionality 

### PR DESCRIPTION
**Pull request by Feruzka1706**
this is the pull request after protecting the master branch

### CODE REVIEW

**Comment by ahmadsam33r** [comment]
great

**Review by nazliSDET — APPROVED** [review]

**Review by AteequllahS — APPROVED** [review]
got approved

**Review by ahmadsam33r — APPROVED** [review]
approved

**Comment by ahmetYilmaz88** [comment]
nice

**Review by ahmetYilmaz88 — COMMENTED** [review]
cool work

**Comment by ahmetYilmaz88** [comment]
Just approved it.

**Pull request merged**
