### PR TITLE
Ateeq branch added

### PR DESCRIPTION
**Pull request by AteequllahS**
I created a branch named Ateeq, ready to be merged.

### CODE REVIEW

**Comment by gulistan33** [comment]
hello Ateequallah

**Review by ahmadsam33r — COMMENTED** [review]
nice job

**Review by gulistan33 — APPROVED** [review]
approving

**Comment by nazliSDET** [comment]
Good job!

**Comment by yahya09206** [comment]
looks good to me

**Comment by Feruzka1706** [comment]
good job

**Pull request merged**
