### PR TITLE
logout

### PR DESCRIPTION
**Pull request by ahmetYilmaz88**
logout

### CODE REVIEW

**Comment by ahmetYilmaz88** [comment]
review please

**Comment by gulistan33** [comment]
nice work

**Comment by gulistan33** [comment]
it says branch has conflict. what should I do?

**Comment by ahmetYilmaz88** [comment]
anyone wanna review this?

**Comment by ahmetYilmaz88** [comment]
it should say that, you just need to review and it will work.

**Review by ahmadsam33r — COMMENTED** [review]
reviewed but from GitHub.com because I didn't got any pull request from IntelliJ .

**Review by ahmetYilmaz88 — COMMENTED** [review]
ok cool

**Review by nazliSDET — APPROVED** [review]

**Comment by nazliSDET** [comment]
great job!

**Review by gulistan33 — APPROVED** [review]

**Pull request closed without merging**
