### PR TITLE
Nazli z001

### PR DESCRIPTION
**Pull request by nazliSDET**
Good morning Group2
  Group2 work has started
   We have good collaboration!

### CODE REVIEW

**Comment by yahya09206** [comment]
looks good to me

**Review by yahya09206 — COMMENTED** [review]
looks good to me

**Review by AteequllahS — APPROVED** [review]
it is great. lets merge it.

**Review by ahmadsam33r — COMMENTED** [review]
great

**Comment by ahmetYilmaz88** [comment]
hello

**Review by ahmetYilmaz88 — APPROVED** [review]
cool code

**Review by gulistan33 — APPROVED** [review]
approving

**Pull request merged**
